package javatutorial;

import java.io.FileWriter;
import java.io.IOException;

public class Practice113 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		try {
			FileWriter write = new FileWriter("MyFile.txt", true);
			System.out.println(10 / 0);
			write.write("hello world");
			write.write("\n");
			write.write("hello ganesh");
			write.close();
		} catch (IOException e) {
			// to do autogenerated catch block
			e.printStackTrace();
		} catch (ArithmeticException e) {
			// to do auto-generated catch block
			e.printStackTrace();
			System.out.println(e.getMessage());

		}

	}

}
